version: '3'
services:
    db:
        image: mongo:3.4.2
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
    simc:
        image: cmatheny/simc:latest
        build: api/simc
        environment:
            APIKEY:  ${APIKEY}
    api:
        build: api/main
        ports:
            - "5000:5000"
        depends_on:
            - db
volumes:
    mongodata:
