version: '3'
services:
    db:
        image: mvertes/alpine-mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
    simc:
        image: cmatheny/simc:latest
        build: api/simc
        entrypoint: [ "/bin/sh" ]
        environment:
            APIKEY:  ${APIKEY}
    simc-api:
        image: cmatheny/simc-api:latest
        build: api/simc-api
        ports:
            - "15001:8888"
        environment:
            APIKEY:  ${APIKEY}
    api:
        image: cmatheny/wow-char-sim-api
        build: api/main
        ports:
            - "5000:5000"
        depends_on:
            - db
            - simc-api
volumes:
    mongodata:
